# Run CMake configure/build for Windows (MSYS2)
name: 'run-cmake-windows'
description: 'Composite action for run-cmake-windows'
runs:
  using: 'composite'
  steps:
  - name: Configure CMake (Windows)
    if: runner.os == 'Windows'
    shell: msys2 {0}
    run: |
      cmake -S . -B build -Wno-dev -G 'MinGW Makefiles' -DBUILD_BINARIES=OFF -DBUILD_PRODUCTS=ON -DBUILD_PRODUCT_INSTALLER_ABSTRACTIONS=ON -DBUILD_IO_SQL=ON -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH='/mingw64'
