FROM ubuntu:22.04
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /opt/plang_lsp
COPY dist/plang_lsp ./plang_lsp
EXPOSE 0
ENTRYPOINT ["/opt/plang_lsp/plang_lsp"]
