# Install script for directory: /Users/mehranghamaty/Documents/GitHub/CoolBox/_libraries

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set path to fallback-tool for dependency-resolution.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/usr/bin/objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/MISC/thread_pool/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/IO/advanced_logging/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/DATASTRUCTURE/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/PARSER/database/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/PARSER/programming_language/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/PARSER/vhdl/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/PARSER/matlab/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/TOOLS/lsp/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/TOOLS/lsp_vhdl/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/TOOLS/lsp_matlab/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/PARSER/javascript/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/IO/dataformats/json/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/IO/distributed/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/IO/file_system/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/MISC/hash/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/MISC/cryptocurrency/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/SECURITY/auth/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/IO/servlets/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/IO/http_server/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/gen_docs/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/MISC/metadata_management/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/MISC/unix_commands/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/MISC/system_stats/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/MISC/wave_generator/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/bayesian_network_ai/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/computer_vision/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/decision_tree/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/deep_learning/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/dimensionality_reduction/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/distribution/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/generalized_linear_model/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/hidden_markov_model/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/latent_sentiment_analysis/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/marked_point_process/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/multi_arm_bandit/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/nlp/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/support_vector_machine/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/time_series/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/tracker/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/self_organizing_maps/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/vae/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/knn/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ML/gabor_patches/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/SECURITY/fuzzer/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/SECURITY/malware_scanner/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/SECURITY/network_scanner/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/GRAPHICS/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/GRAPHICS/charts/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/GRAPHICS/fonts/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/GRAPHICS/components/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/GRAPHICS/windows/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ELECTRONICS/curcuitry/cmake_install.cmake")
  include("/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/backages/ELECTRONICS/battery/cmake_install.cmake")

endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
if(CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "/Users/mehranghamaty/Documents/GitHub/CoolBox/build_lsp/_libraries/install_local_manifest.txt"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
