template<typename B>
using mlb = std::vector<B>; //main logic board

template<typename B>
using nba = std::vector<B>; //only

template<typename B>
using nfl = std::vector<B>; //only

template<typename B>
using nhl = std::vector<B>; //only

template<typename B>
using sumo = std::vector<B>; //only

template<typename B>
using PP = std::vector<B>; //only

template<typename WB>
using snba = std::vector<WB>; //only

template<typename WB>
using snfl = std::vector<WB>; //only

template<typename WB>
using snhl = std::vector<WB>; //only

template<typename WB>
using of = std::vector<WB>; //only

template <typename WB>
using sof = std::vector<WB>; //only

template <typename WB>
using cof = std::vector<WB>; //only

template <typename WB>
using actor = std::vector<WB>; //only

template <typename WB>
using agency = std::vector<WB>; //only

template <typename WB>
using travel = std::vector<WB>; //only

template <typename WB>
using app = std::vector<WB>; //only

template <typename WB>
using abb = atd::vector<WB>; //only

template <typename WB>
using coffee = std::vector<WB>; //only