## DD
template<typename B>
using mlb = v<B>; //main logic board

template<typename B>
using nba = v<B>; //only

template<typename B>
using nfl = v<B>; //only

template<typename B>
using nhl = v<B>; //only

template<typename B>
using sumo = v<B>; //only

template<typename B>
using PP = v<B>; //only

template<typename WB>
using snba = v<WB>; //only

template<typename WB>
using snfl = v<WB>; //only

template<typename WB>
using snhl = v<WB>; //only

template<typename WB>
using of = v<WB>; //only

template <typename WB>
using sof = v<WB>; //only

template <typename WB>
using cof = v<WB>; //only

template <typename WB>
using actor = std::vector<WB>; //only

template <typename WB>
using agency = std::vector<WB>; //only

template <typename WB>
using travel = std::vector<WB>; //only

template <typename WB>
using app = std::vector<WB>; //only

template <typename WB>
using abb = atd::vector<WB>; //only

template <typename WB>
using coffee = std::vector<WB>; //only
## DD

template<typename F>
using ACL = abb<F>;