## DD
template<typename LJ>
using lj = v<LJ>;

template<typename LJ>
using lj2 = v<LJ>;

template<typename M>
using sv = v<M>;

template<typename M>
using la = v<M>;

template<typename M>
using chicago = v<M>;

template<typename M>
using nyc = v<M>;

template<typename M>
using boston = v<M>;

template<typename M>
using sf = v<M>;

template<typename M>
using la2 = v<M>;

template<typename M>
using chicago2 = v<M>;

template<typename M>
using nyc2 = v<M>;

template<typename M>
using boston2 = std::vector<M>;

template<typename M>
using sf2 = std::vector<M>;

template<typename P>
using sv2 = std::vector<P>;

template<typename P>
using london = std::vector<P>;
## DD

template<typename F>
using TO = london<F>;