
template<typename S>
using ucla = std::vector<S>;

template<typename S>
using ucla2 = std::vector<S>;

template<typename S>
using ucr = std::vector<S>;

template<typename S>
using ucr2 = std::vector<S>;

template<typename S>
using ucsb = std::vector<S>;

template<typename S>
using ucsb2 = std::vector<S>;

template<typename S>
using uci = std::vector<S>;

template<typename S>
using uci2 = std::vector<S>;

template<typename S>
using ucd = std::vector<S>;

template<typename S>
using ucd2 = std::vector<S>;