
# DD
template<typename S>
using ucla = v<S>;

template<typename S>
using ucla2 = v<S>;

template<typename S>
using ucr = v<S>;

template<typename S>
using ucr2 = v<S>;

template<typename S>
using ucsb = v<S>;

template<typename S>
using ucsb2 = v<S>;

template<typename S>
using uci = v<S>;

template<typename S>
using uci2 = v<S>;

template<typename S>
using ucd = v<S>;

template<typename S>
using ucd2 = v<S>;

template<typename S>
using ucm = v<S>;

template<typename S>
using ucm2 = v<S>;

template<typename S>
using ucsd = v<S>;

template<typename S>
using ucsd2 = v<S>;
# DD

template<typename F>
using UNI = ucsd<F>;