# Run CMake configure/build for Linux
name: 'run-cmake-linux'
description: 'Composite action for run-cmake-linux'
runs:
  using: 'composite'
  steps:
  - name: Configure CMake (Linux)
    if: runner.os == 'Linux'
    shell: bash
    run: |
      cmake -S . -B build -DBUILD_BINARIES=ON -DCMAKE_BUILD_TYPE=Release
      cmake --build build --parallel
