#ifndef COOLBOX__LIBRARIES_BACKAGES_TOOLS_LSP_PYTHON_HEADERS_LSP_SERVER_PYTHON_H
#define COOLBOX__LIBRARIES_BACKAGES_TOOLS_LSP_PYTHON_HEADERS_LSP_SERVER_PYTHON_H
#include <string>

std::string python_process_text_for_diagnostics(const std::string &uri, const std::string &text);

#endif  // COOLBOX__LIBRARIES_BACKAGES_TOOLS_LSP_PYTHON_HEADERS_LSP_SERVER_PYTHON_H
