FROM ubuntu:22.04
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /opt/plvlang_lsp
COPY dist/plvlang_lsp ./plvlang_lsp
EXPOSE 0
ENTRYPOINT ["/opt/plvlang_lsp/plvlang_lsp"]