// This file is generated by Rcpp::compileAttributes (do not edit by hand)
#include <Rcpp.h>

// [[Rcpp::interfaces(r, cpp)]]

// Placeholders for GUI primitive bindings

// Toolbar
// [[Rcpp::export]]
SEXP Toolbar_create(Rcpp::CharacterVector actions);
// [[Rcpp::export]]
void Toolbar_free(SEXP handle);

// DockPanel
// [[Rcpp::export]]
SEXP DockPanel_create(Rcpp::String title, bool floating);
// [[Rcpp::export]]
void DockPanel_free(SEXP handle);

// LayerList
// [[Rcpp::export]]
SEXP LayerList_create(Rcpp::CharacterVector layers, int selected);
// [[Rcpp::export]]
void LayerList_free(SEXP handle);

// PropertyInspector
// [[Rcpp::export]]
SEXP PropertyInspector_create(Rcpp::CharacterVector keys, Rcpp::CharacterVector values);
// [[Rcpp::export]]
void PropertyInspector_free(SEXP handle);

// FileTree
// [[Rcpp::export]]
SEXP FileTree_create(Rcpp::String rootName);
// [[Rcpp::export]]
void FileTree_free(SEXP handle);

// RadioSelector
// [[Rcpp::export]]
SEXP RadioSelector_create(Rcpp::CharacterVector options, int selected);
// [[Rcpp::export]]
void RadioSelector_free(SEXP handle);

// CheckboxGroup
// [[Rcpp::export]]
SEXP CheckboxGroup_create(Rcpp::CharacterVector options, Rcpp::LogicalVector checked);
// [[Rcpp::export]]
void CheckboxGroup_free(SEXP handle);

// Implementations will be provided in RcppExports_wrap.cpp
