#include "bridge.h"

#include "../backages/ML/generalized_linear_model/headers/generalized_linear_model.h"
#include "../backages/ML/generalized_linear_model/headers/linear_regression.h"
#include "../backages/ML/decision_tree/headers/decision_tree.h"
#include "../backages/ML/bayesian_network_ai/headers/bayesian_network.h"
#include "../backages/ML/hidden_markov_model/headers/hidden_markov_model.h"
#include "../backages/ML/dimensionality_reduction/headers/pca.h"
#include "../backages/ML/support_vector_machine/headers/support_vector_machine.h"
#include "../backages/ML/support_vector_machine/headers/linear_kernel.h"
#include "../backages/ML/support_vector_machine/headers/rbf_kernel.h"
#include "../backages/ML/support_vector_machine/headers/polynomial_kernel.h"
#include "../backages/ML/support_vector_machine/headers/sigmoid_kernel.h"
#include "../backages/ML/multi_arm_bandit/headers/bandit_arm.h"
#include "../backages/ML/multi_arm_bandit/headers/bandit_agent.h"
#include "../backages/ML/multi_arm_bandit/headers/epsilon_greedy_agent.h"
#include "../backages/ML/multi_arm_bandit/headers/ucb_agent.h"
#include "../backages/ML/multi_arm_bandit/headers/thompson_sampling_agent.h"
#include "../backages/ML/multi_arm_bandit/headers/decaying_epsilon_agent.h"

#include <Eigen/Dense>

#include <algorithm>
#include <cstring>
#include <cstdlib>
#include <memory>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include "../backages/ML/generalized_linear_model/source/generalized_linear_model.cpp"
#include "../backages/ML/generalized_linear_model/source/linear_regression.cpp"
#include "../backages/ML/decision_tree/source/decision_tree.cpp"
#include "../backages/ML/bayesian_network_ai/source/bayesian_network.cpp"
#include "../backages/ML/hidden_markov_model/source/hidden_markov_model.cpp"
#include "../backages/ML/dimensionality_reduction/source/svd.cpp"
#include "../backages/ML/dimensionality_reduction/source/pca.cpp"
#include "../backages/ML/support_vector_machine/source/linear_kernel.cpp"
#include "../backages/ML/support_vector_machine/source/rbf_kernel.cpp"
#include "../backages/ML/support_vector_machine/source/polynomial_kernel.cpp"
#include "../backages/ML/support_vector_machine/source/sigmoid_kernel.cpp"
#include "../backages/ML/support_vector_machine/source/support_vector_machine.cpp"
#include "../backages/ML/multi_arm_bandit/source/bandit_arm.cpp"
#include "../backages/ML/multi_arm_bandit/source/bandit_agent.cpp"
#include "../backages/ML/multi_arm_bandit/source/epsilon_greedy_agent.cpp"
#include "../backages/ML/multi_arm_bandit/source/ucb_agent.cpp"
#include "../backages/ML/multi_arm_bandit/source/thompson_sampling_agent.cpp"
#include "../backages/ML/multi_arm_bandit/source/decaying_epsilon_agent.cpp"
#include "../backages/ML/multi_arm_bandit/source/simulation_result.cpp"

using dimensionality_reduction::PCA;

struct CoolBoxLinearRegressionModel { std::vector<double> weights; double intercept; std::string method; };
struct CoolBoxDecisionTreeModel { explicit CoolBoxDecisionTreeModel(SplitCriterion criterion) : tree(criterion) {} DecisionTree tree; };
struct CoolBoxBayesianNetworkModel { BayesianNetwork network; };
struct CoolBoxHMMModel { CoolBoxHMMModel(std::size_t state_count, std::size_t observation_count) : hmm(static_cast<int>(state_count), static_cast<int>(observation_count)), states(state_count), observations(observation_count) {} HMM hmm; std::size_t states; std::size_t observations; };
struct CoolBoxPCAModel { CoolBoxPCAModel(int n_components, bool center, bool scale) : pca(n_components, center, scale), feature_count(0) {} PCA pca; std::size_t feature_count; };
struct CoolBoxSVMModel { std::unique_ptr<Kernel> kernel; std::unique_ptr<SVM> svm; std::size_t feature_count; };
struct CoolBoxBanditArmModel { explicit CoolBoxBanditArmModel(double true_reward_prob) : arm(true_reward_prob) {} BanditArm arm; };
struct CoolBoxBanditAgentModel { explicit CoolBoxBanditAgentModel(std::unique_ptr<BanditAgent> value) : agent(std::move(value)) {} std::unique_ptr<BanditAgent> agent; };

namespace {

char* copy_error_message(const std::string& message) { char* out = static_cast<char*>(std::malloc(message.size() + 1)); if (out == nullptr) { return nullptr; } std::memcpy(out, message.c_str(), message.size() + 1); return out; }
void assign_error(char** error_message, const std::string& message) { if (error_message != nullptr) { *error_message = copy_error_message(message); } }
void clear_error(char** error_message) { if (error_message != nullptr) { *error_message = nullptr; } }

std::vector<std::vector<double>> to_matrix(const double* x_flat, size_t rows, size_t cols) { if (x_flat == nullptr) throw std::invalid_argument("feature matrix pointer must not be null"); if (rows == 0 || cols == 0) throw std::invalid_argument("feature matrix must be non-empty"); std::vector<std::vector<double>> matrix(rows, std::vector<double>(cols)); for (size_t i = 0; i < rows; ++i) for (size_t j = 0; j < cols; ++j) matrix[i][j] = x_flat[i * cols + j]; return matrix; }
std::vector<std::vector<int>> to_int_matrix(const int* x_flat, size_t rows, size_t cols) { if (x_flat == nullptr) throw std::invalid_argument("feature matrix pointer must not be null"); if (rows == 0 || cols == 0) throw std::invalid_argument("feature matrix must be non-empty"); std::vector<std::vector<int>> matrix(rows, std::vector<int>(cols)); for (size_t i = 0; i < rows; ++i) for (size_t j = 0; j < cols; ++j) matrix[i][j] = x_flat[i * cols + j]; return matrix; }
std::vector<double> to_vector(const double* values, size_t size) { if (values == nullptr) throw std::invalid_argument("value pointer must not be null"); return std::vector<double>(values, values + size); }
std::vector<int> to_int_vector(const int* values, size_t size) { if (values == nullptr) throw std::invalid_argument("value pointer must not be null"); return std::vector<int>(values, values + size); }
Eigen::MatrixXd to_eigen_matrix(const double* values, size_t rows, size_t cols) { if (values == nullptr) throw std::invalid_argument("matrix pointer must not be null"); if (rows == 0 || cols == 0) throw std::invalid_argument("matrix must be non-empty"); Eigen::MatrixXd matrix(static_cast<Eigen::Index>(rows), static_cast<Eigen::Index>(cols)); for (size_t i = 0; i < rows; ++i) for (size_t j = 0; j < cols; ++j) matrix(static_cast<Eigen::Index>(i), static_cast<Eigen::Index>(j)) = values[i * cols + j]; return matrix; }
Eigen::VectorXd to_eigen_vector(const double* values, size_t size) { if (values == nullptr) throw std::invalid_argument("vector pointer must not be null"); Eigen::VectorXd vector(static_cast<Eigen::Index>(size)); for (size_t i = 0; i < size; ++i) vector(static_cast<Eigen::Index>(i)) = values[i]; return vector; }
void copy_vector_to_buffer(const std::vector<double>& values, double* out_values, size_t out_count, const char* label) { if (out_values == nullptr) throw std::invalid_argument(std::string(label) + " output pointer must not be null"); if (out_count < values.size()) throw std::invalid_argument(std::string(label) + " output buffer is too small"); std::copy(values.begin(), values.end(), out_values); }
void copy_eigen_vector_to_buffer(const Eigen::VectorXd& values, double* out_values, size_t out_count, const char* label) { if (out_values == nullptr) throw std::invalid_argument(std::string(label) + " output pointer must not be null"); if (out_count < static_cast<size_t>(values.size())) throw std::invalid_argument(std::string(label) + " output buffer is too small"); for (Eigen::Index i = 0; i < values.size(); ++i) out_values[static_cast<size_t>(i)] = values(i); }
void copy_eigen_matrix_to_buffer(const Eigen::MatrixXd& values, double* out_values, size_t out_count, const char* label) { if (out_values == nullptr) throw std::invalid_argument(std::string(label) + " output pointer must not be null"); const size_t required = static_cast<size_t>(values.rows() * values.cols()); if (out_count < required) throw std::invalid_argument(std::string(label) + " output buffer is too small"); for (Eigen::Index i = 0; i < values.rows(); ++i) for (Eigen::Index j = 0; j < values.cols(); ++j) out_values[static_cast<size_t>(i * values.cols() + j)] = values(i, j); }
SplitCriterion parse_split_criterion(const std::string& value) { return value == "entropy" ? SplitCriterion::ENTROPY : SplitCriterion::GINI; }
std::map<int, int> make_evidence_map(const int* node_ids, const int* state_ids, size_t evidence_count) { if (evidence_count == 0) return {}; if (node_ids == nullptr || state_ids == nullptr) throw std::invalid_argument("evidence pointers must not be null when evidence is provided"); std::map<int, int> evidence; for (size_t i = 0; i < evidence_count; ++i) evidence[node_ids[i]] = state_ids[i]; return evidence; }
std::vector<std::vector<int>> make_sequences(const int* sequences_flat, const size_t* sequence_lengths, size_t sequence_count) { if (sequence_count == 0) throw std::invalid_argument("at least one observation sequence is required"); if (sequences_flat == nullptr || sequence_lengths == nullptr) throw std::invalid_argument("sequence pointers must not be null"); std::vector<std::vector<int>> sequences; sequences.reserve(sequence_count); size_t offset = 0; for (size_t i = 0; i < sequence_count; ++i) { if (sequence_lengths[i] == 0) throw std::invalid_argument("observation sequences must be non-empty"); sequences.emplace_back(sequences_flat + offset, sequences_flat + offset + sequence_lengths[i]); offset += sequence_lengths[i]; } return sequences; }
std::unique_ptr<Kernel> create_kernel(const std::string& kernel_type, double param1, double param2, int param3) { if (kernel_type == "linear") return std::make_unique<LinearKernel>(); if (kernel_type == "rbf") return std::make_unique<RBFKernel>(param1); if (kernel_type == "polynomial") return std::make_unique<PolynomialKernel>(param1, param2, param3); if (kernel_type == "sigmoid") return std::make_unique<SigmoidKernel>(param1, param2); throw std::invalid_argument("unsupported kernel type: " + kernel_type); }
template <typename Factory> CoolBoxBanditAgentModel* make_bandit_agent(Factory&& factory, char** error_message) { try { clear_error(error_message); return new CoolBoxBanditAgentModel(factory()); } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return nullptr; } catch (...) { assign_error(error_message, "unknown C++ exception while creating bandit agent"); return nullptr; } }

} // namespace

extern "C" {

CoolBoxLinearRegressionModel* coolbox_fit_linear_regression(const double* x_flat, size_t rows, size_t cols, const double* y, const char* method, uint32_t iterations, double learning_rate, char** error_message) { try { clear_error(error_message); if (method == nullptr) throw std::invalid_argument("fit method must not be null"); auto x = to_matrix(x_flat, rows, cols); auto y_vec = to_vector(y, rows); std::string method_string(method); auto fit_type = method_string == "gradient_descent" ? LinearRegressionFitMethod::GRADIENT_DESCENT : LinearRegressionFitMethod::CLOSED_FORM; LinearRegressionFitMethod fit_method(iterations, learning_rate, fit_type); LinearRegression model(fit_method); model.fit(x, y_vec); auto coefficients = model.get_coefficients(); return new CoolBoxLinearRegressionModel{coefficients.first, coefficients.second, method_string}; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return nullptr; } catch (...) { assign_error(error_message, "unknown C++ exception while fitting linear regression"); return nullptr; } }
int coolbox_predict_linear_regression(const CoolBoxLinearRegressionModel* model, const double* x_flat, size_t rows, size_t cols, double* out_predictions, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("model pointer must not be null"); if (out_predictions == nullptr) throw std::invalid_argument("prediction output pointer must not be null"); if (cols != model->weights.size()) throw std::invalid_argument("feature column count must match the fitted model"); auto x = to_matrix(x_flat, rows, cols); for (size_t i = 0; i < rows; ++i) { double fitted = model->intercept; for (size_t j = 0; j < cols; ++j) fitted += x[i][j] * model->weights[j]; out_predictions[i] = fitted; } return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while predicting linear regression"); return 0; } }
size_t coolbox_linear_regression_feature_count(const CoolBoxLinearRegressionModel* model) { return model == nullptr ? 0 : model->weights.size(); }
double coolbox_linear_regression_intercept(const CoolBoxLinearRegressionModel* model) { return model == nullptr ? 0.0 : model->intercept; }
double coolbox_linear_regression_weight_at(const CoolBoxLinearRegressionModel* model, size_t index) { return (model == nullptr || index >= model->weights.size()) ? 0.0 : model->weights[index]; }
const char* coolbox_linear_regression_method_name(const CoolBoxLinearRegressionModel* model) { return model == nullptr ? "" : model->method.c_str(); }
void coolbox_free_linear_regression(CoolBoxLinearRegressionModel* model) { delete model; }

CoolBoxDecisionTreeModel* coolbox_create_decision_tree(const char* criterion, char** error_message) { try { clear_error(error_message); const std::string value = criterion == nullptr ? "gini" : std::string(criterion); return new CoolBoxDecisionTreeModel(parse_split_criterion(value)); } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return nullptr; } catch (...) { assign_error(error_message, "unknown C++ exception while creating decision tree"); return nullptr; } }
int coolbox_decision_tree_fit(CoolBoxDecisionTreeModel* model, const int* x_flat, size_t rows, size_t cols, const int* y, int max_depth, char** error_message) { try { clear_error(error_message); if (model == nullptr || y == nullptr) throw std::invalid_argument("decision tree input pointers must not be null"); model->tree.fit(to_int_matrix(x_flat, rows, cols), to_int_vector(y, rows), max_depth); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while fitting decision tree"); return 0; } }
int coolbox_decision_tree_predict(const CoolBoxDecisionTreeModel* model, const int* sample, size_t feature_count, int* out_label, char** error_message) { try { clear_error(error_message); if (model == nullptr || sample == nullptr || out_label == nullptr) throw std::invalid_argument("decision tree input pointers must not be null"); *out_label = model->tree.predict(to_int_vector(sample, feature_count)); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while predicting decision tree"); return 0; } }
void coolbox_free_decision_tree(CoolBoxDecisionTreeModel* model) { delete model; }

CoolBoxBayesianNetworkModel* coolbox_create_bayesian_network(void) { return new CoolBoxBayesianNetworkModel{}; }
int coolbox_bayesian_network_add_node(CoolBoxBayesianNetworkModel* model, const char* name, const char* const* states, size_t state_count, int* out_node_id, char** error_message) { try { clear_error(error_message); if (model == nullptr || name == nullptr || out_node_id == nullptr) throw std::invalid_argument("bayesian network input pointers must not be null"); if (state_count == 0 || states == nullptr) throw std::invalid_argument("at least one state is required"); std::vector<std::string> state_values; state_values.reserve(state_count); for (size_t i = 0; i < state_count; ++i) { if (states[i] == nullptr) throw std::invalid_argument("state strings must not be null"); state_values.emplace_back(states[i]); } *out_node_id = model->network.add_node(name, state_values); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while adding bayesian network node"); return 0; } }
int coolbox_bayesian_network_add_edge(CoolBoxBayesianNetworkModel* model, int parent_id, int child_id, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("bayesian network pointer must not be null"); model->network.add_edge(parent_id, child_id); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while adding bayesian network edge"); return 0; } }
int coolbox_bayesian_network_set_cpt(CoolBoxBayesianNetworkModel* model, int node_id, const double* values, size_t value_count, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("bayesian network pointer must not be null"); model->network.set_cpt(node_id, to_vector(values, value_count)); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while setting bayesian network CPT"); return 0; } }
size_t coolbox_bayesian_network_num_nodes(const CoolBoxBayesianNetworkModel* model) { return model == nullptr ? 0 : static_cast<size_t>(model->network.num_nodes()); }
int coolbox_bayesian_network_get_node_id(const CoolBoxBayesianNetworkModel* model, const char* name, int* out_node_id, char** error_message) { try { clear_error(error_message); if (model == nullptr || name == nullptr || out_node_id == nullptr) throw std::invalid_argument("bayesian network input pointers must not be null"); *out_node_id = model->network.get_node_id(name); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while looking up bayesian network node"); return 0; } }
int coolbox_bayesian_network_get_node_state_count(const CoolBoxBayesianNetworkModel* model, int node_id, size_t* out_state_count, char** error_message) { try { clear_error(error_message); if (model == nullptr || out_state_count == nullptr) throw std::invalid_argument("bayesian network input pointers must not be null"); *out_state_count = model->network.node(node_id).states.size(); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while fetching bayesian network state count"); return 0; } }
int coolbox_bayesian_network_query(const CoolBoxBayesianNetworkModel* model, int query_node, const int* evidence_node_ids, const int* evidence_state_ids, size_t evidence_count, double* out_distribution, size_t distribution_count, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("bayesian network pointer must not be null"); const auto distribution = model->network.query(query_node, make_evidence_map(evidence_node_ids, evidence_state_ids, evidence_count)); copy_vector_to_buffer(distribution, out_distribution, distribution_count, "distribution"); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while querying bayesian network"); return 0; } }
void coolbox_free_bayesian_network(CoolBoxBayesianNetworkModel* model) { delete model; }

CoolBoxHMMModel* coolbox_create_hmm(size_t states, size_t observations, char** error_message) { try { clear_error(error_message); return new CoolBoxHMMModel(states, observations); } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return nullptr; } catch (...) { assign_error(error_message, "unknown C++ exception while creating HMM"); return nullptr; } }
int coolbox_hmm_set_initial_probabilities(CoolBoxHMMModel* model, const double* values, size_t count, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("HMM pointer must not be null"); model->hmm.set_initial_probabilities(to_eigen_vector(values, count)); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while setting HMM initial probabilities"); return 0; } }
int coolbox_hmm_set_transition_matrix(CoolBoxHMMModel* model, const double* values, size_t rows, size_t cols, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("HMM pointer must not be null"); model->hmm.set_transition_matrix(to_eigen_matrix(values, rows, cols)); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while setting HMM transition matrix"); return 0; } }
int coolbox_hmm_set_emission_matrix(CoolBoxHMMModel* model, const double* values, size_t rows, size_t cols, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("HMM pointer must not be null"); model->hmm.set_emission_matrix(to_eigen_matrix(values, rows, cols)); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while setting HMM emission matrix"); return 0; } }
int coolbox_hmm_get_initial_probabilities(const CoolBoxHMMModel* model, double* out_values, size_t count, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("HMM pointer must not be null"); copy_eigen_vector_to_buffer(model->hmm.get_initial_probabilities(), out_values, count, "initial probabilities"); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while getting HMM initial probabilities"); return 0; } }
int coolbox_hmm_get_transition_matrix(const CoolBoxHMMModel* model, double* out_values, size_t rows, size_t cols, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("HMM pointer must not be null"); copy_eigen_matrix_to_buffer(model->hmm.get_transition_matrix(), out_values, rows * cols, "transition matrix"); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while getting HMM transition matrix"); return 0; } }
int coolbox_hmm_get_emission_matrix(const CoolBoxHMMModel* model, double* out_values, size_t rows, size_t cols, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("HMM pointer must not be null"); copy_eigen_matrix_to_buffer(model->hmm.get_emission_matrix(), out_values, rows * cols, "emission matrix"); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while getting HMM emission matrix"); return 0; } }
int coolbox_hmm_log_likelihood(const CoolBoxHMMModel* model, const int* observations, size_t observation_count, double* out_value, char** error_message) { try { clear_error(error_message); if (model == nullptr || out_value == nullptr) throw std::invalid_argument("HMM input pointers must not be null"); *out_value = model->hmm.log_likelihood(to_int_vector(observations, observation_count)); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while computing HMM log likelihood"); return 0; } }
int coolbox_hmm_get_most_likely_states(const CoolBoxHMMModel* model, const int* observations, size_t observation_count, int* out_states, size_t state_count, char** error_message) { try { clear_error(error_message); if (model == nullptr || out_states == nullptr) throw std::invalid_argument("HMM input pointers must not be null"); const auto states = model->hmm.get_most_likely_states(to_int_vector(observations, observation_count)); if (state_count < states.size()) throw std::invalid_argument("output state buffer is too small"); std::copy(states.begin(), states.end(), out_states); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while decoding HMM states"); return 0; } }
int coolbox_hmm_train(CoolBoxHMMModel* model, const int* sequences_flat, const size_t* sequence_lengths, size_t sequence_count, int max_iterations, double tolerance, double smoothing_factor, uint32_t seed, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("HMM pointer must not be null"); model->hmm.train(make_sequences(sequences_flat, sequence_lengths, sequence_count), max_iterations, tolerance, smoothing_factor, seed); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while training HMM"); return 0; } }
void coolbox_free_hmm(CoolBoxHMMModel* model) { delete model; }

CoolBoxPCAModel* coolbox_create_pca(int n_components, int center, int scale, char** error_message) { try { clear_error(error_message); return new CoolBoxPCAModel(n_components, center != 0, scale != 0); } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return nullptr; } catch (...) { assign_error(error_message, "unknown C++ exception while creating PCA"); return nullptr; } }
int coolbox_pca_fit(CoolBoxPCAModel* model, const double* x_flat, size_t rows, size_t cols, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("PCA pointer must not be null"); model->pca.fit(to_eigen_matrix(x_flat, rows, cols)); model->feature_count = cols; return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while fitting PCA"); return 0; } }
int coolbox_pca_transform(const CoolBoxPCAModel* model, const double* x_flat, size_t rows, size_t cols, double* out_values, size_t out_count, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("PCA pointer must not be null"); copy_eigen_matrix_to_buffer(model->pca.transform(to_eigen_matrix(x_flat, rows, cols)), out_values, out_count, "PCA transform"); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while transforming PCA data"); return 0; } }
int coolbox_pca_fit_transform(CoolBoxPCAModel* model, const double* x_flat, size_t rows, size_t cols, double* out_values, size_t out_count, size_t* out_cols, char** error_message) { try { clear_error(error_message); if (model == nullptr || out_cols == nullptr) throw std::invalid_argument("PCA input pointers must not be null"); const Eigen::MatrixXd transformed = model->pca.fit_transform(to_eigen_matrix(x_flat, rows, cols)); model->feature_count = cols; *out_cols = static_cast<size_t>(transformed.cols()); copy_eigen_matrix_to_buffer(transformed, out_values, out_count, "PCA fit_transform"); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while fit-transforming PCA data"); return 0; } }
int coolbox_pca_inverse_transform(const CoolBoxPCAModel* model, const double* x_flat, size_t rows, size_t cols, double* out_values, size_t out_count, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("PCA pointer must not be null"); copy_eigen_matrix_to_buffer(model->pca.inverse_transform(to_eigen_matrix(x_flat, rows, cols)), out_values, out_count, "PCA inverse_transform"); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while inverse-transforming PCA data"); return 0; } }
int coolbox_pca_get_components(const CoolBoxPCAModel* model, double* out_values, size_t out_count, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("PCA pointer must not be null"); copy_eigen_matrix_to_buffer(model->pca.get_components(), out_values, out_count, "PCA components"); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while getting PCA components"); return 0; } }
int coolbox_pca_get_explained_variance(const CoolBoxPCAModel* model, double* out_values, size_t out_count, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("PCA pointer must not be null"); copy_eigen_vector_to_buffer(model->pca.get_explained_variance(), out_values, out_count, "PCA explained variance"); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while getting PCA explained variance"); return 0; } }
int coolbox_pca_get_explained_variance_ratio(const CoolBoxPCAModel* model, double* out_values, size_t out_count, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("PCA pointer must not be null"); copy_eigen_vector_to_buffer(model->pca.get_explained_variance_ratio(), out_values, out_count, "PCA explained variance ratio"); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while getting PCA explained variance ratio"); return 0; } }
int coolbox_pca_get_singular_values(const CoolBoxPCAModel* model, double* out_values, size_t out_count, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("PCA pointer must not be null"); copy_eigen_vector_to_buffer(model->pca.get_singular_values(), out_values, out_count, "PCA singular values"); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while getting PCA singular values"); return 0; } }
int coolbox_pca_get_mean(const CoolBoxPCAModel* model, double* out_values, size_t out_count, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("PCA pointer must not be null"); copy_eigen_vector_to_buffer(model->pca.get_mean(), out_values, out_count, "PCA mean"); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while getting PCA mean"); return 0; } }
int coolbox_pca_get_scale(const CoolBoxPCAModel* model, double* out_values, size_t out_count, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("PCA pointer must not be null"); copy_eigen_vector_to_buffer(model->pca.get_scale(), out_values, out_count, "PCA scale"); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while getting PCA scale"); return 0; } }
size_t coolbox_pca_component_count(const CoolBoxPCAModel* model) { if (model == nullptr || !model->pca.is_fitted()) return 0; return static_cast<size_t>(model->pca.get_components().cols()); }
size_t coolbox_pca_feature_count(const CoolBoxPCAModel* model) { return model == nullptr ? 0 : model->feature_count; }
int coolbox_pca_is_fitted(const CoolBoxPCAModel* model) { return model != nullptr && model->pca.is_fitted() ? 1 : 0; }
void coolbox_free_pca(CoolBoxPCAModel* model) { delete model; }

CoolBoxSVMModel* coolbox_create_svm(const char* kernel_type, double param1, double param2, int param3, char** error_message) { try { clear_error(error_message); if (kernel_type == nullptr) throw std::invalid_argument("kernel type must not be null"); auto kernel = create_kernel(kernel_type, param1, param2, param3); auto svm = std::make_unique<SVM>(*kernel); auto* model = new CoolBoxSVMModel{}; model->kernel = std::move(kernel); model->svm = std::move(svm); model->feature_count = 0; return model; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return nullptr; } catch (...) { assign_error(error_message, "unknown C++ exception while creating SVM"); return nullptr; } }
int coolbox_svm_fit(CoolBoxSVMModel* model, const double* x_flat, size_t rows, size_t cols, const double* y, size_t y_count, char** error_message) { try { clear_error(error_message); if (model == nullptr || model->svm == nullptr) throw std::invalid_argument("SVM pointer must not be null"); if (rows != y_count) throw std::invalid_argument("target vector length must match the number of feature rows"); model->svm->fit(to_eigen_matrix(x_flat, rows, cols), to_eigen_vector(y, y_count)); model->feature_count = cols; return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while fitting SVM"); return 0; } }
int coolbox_svm_predict(const CoolBoxSVMModel* model, const double* sample, size_t feature_count, double* out_value, char** error_message) { try { clear_error(error_message); if (model == nullptr || model->svm == nullptr || out_value == nullptr) throw std::invalid_argument("SVM input pointers must not be null"); if (model->feature_count != 0 && model->feature_count != feature_count) throw std::invalid_argument("feature column count must match the fitted model"); *out_value = model->svm->predict(to_eigen_vector(sample, feature_count)); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while predicting SVM"); return 0; } }
void coolbox_free_svm(CoolBoxSVMModel* model) { delete model; }

CoolBoxBanditArmModel* coolbox_create_bandit_arm(double true_reward_prob, char** error_message) { try { clear_error(error_message); return new CoolBoxBanditArmModel(true_reward_prob); } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return nullptr; } catch (...) { assign_error(error_message, "unknown C++ exception while creating bandit arm"); return nullptr; } }
int coolbox_bandit_arm_pull(CoolBoxBanditArmModel* model, double* out_reward, char** error_message) { try { clear_error(error_message); if (model == nullptr || out_reward == nullptr) throw std::invalid_argument("bandit arm input pointers must not be null"); *out_reward = model->arm.pull(); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while pulling bandit arm"); return 0; } }
int coolbox_bandit_arm_update(CoolBoxBanditArmModel* model, double reward, char** error_message) { try { clear_error(error_message); if (model == nullptr) throw std::invalid_argument("bandit arm pointer must not be null"); model->arm.update(reward); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while updating bandit arm"); return 0; } }
double coolbox_bandit_arm_estimated_prob(const CoolBoxBanditArmModel* model) { return model == nullptr ? 0.0 : model->arm.get_estimated_prob(); }
int coolbox_bandit_arm_pull_count(const CoolBoxBanditArmModel* model) { return model == nullptr ? 0 : model->arm.get_pull_count(); }
double coolbox_bandit_arm_true_prob(const CoolBoxBanditArmModel* model) { return model == nullptr ? 0.0 : model->arm.get_true_prob(); }
void coolbox_free_bandit_arm(CoolBoxBanditArmModel* model) { delete model; }

CoolBoxBanditAgentModel* coolbox_create_epsilon_greedy_agent(const double* true_probs, size_t count, double epsilon, double, long long seed, char** error_message) { return make_bandit_agent([&]() { return std::make_unique<EpsilonGreedyAgent>(to_vector(true_probs, count), epsilon, seed); }, error_message); }
CoolBoxBanditAgentModel* coolbox_create_ucb_agent(const double* true_probs, size_t count, double c, double, long long, char** error_message) { return make_bandit_agent([&]() { return std::make_unique<UCBAgent>(to_vector(true_probs, count), c); }, error_message); }
CoolBoxBanditAgentModel* coolbox_create_thompson_sampling_agent(const double* true_probs, size_t count, double, double, long long seed, char** error_message) { return make_bandit_agent([&]() { return std::make_unique<ThompsonSamplingAgent>(to_vector(true_probs, count), seed); }, error_message); }
CoolBoxBanditAgentModel* coolbox_create_decaying_epsilon_greedy_agent(const double* true_probs, size_t count, double initial_epsilon, double decay_rate, long long seed, char** error_message) { return make_bandit_agent([&]() { return std::make_unique<DecayingEpsilonGreedyAgent>(to_vector(true_probs, count), initial_epsilon, decay_rate, seed); }, error_message); }
int coolbox_bandit_agent_run_simulation(CoolBoxBanditAgentModel* model, int num_steps, char** error_message) { try { clear_error(error_message); if (model == nullptr || model->agent == nullptr) throw std::invalid_argument("bandit agent pointer must not be null"); model->agent->run_simulation(num_steps); return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while running bandit simulation"); return 0; } }
size_t coolbox_bandit_agent_arm_count(const CoolBoxBanditAgentModel* model) { return (model == nullptr || model->agent == nullptr) ? 0 : model->agent->get_results().bandit_results.size(); }
int coolbox_bandit_agent_get_results(const CoolBoxBanditAgentModel* model, double* out_true_probs, double* out_estimated_probs, int* out_pull_counts, size_t count, char** error_message) { try { clear_error(error_message); if (model == nullptr || model->agent == nullptr) throw std::invalid_argument("bandit agent pointer must not be null"); if (out_true_probs == nullptr || out_estimated_probs == nullptr || out_pull_counts == nullptr) throw std::invalid_argument("bandit result output pointers must not be null"); const SimulationResult result = model->agent->get_results(); if (count < result.bandit_results.size()) throw std::invalid_argument("bandit result buffers are too small"); for (size_t i = 0; i < result.bandit_results.size(); ++i) { out_true_probs[i] = result.bandit_results[i].true_probability; out_estimated_probs[i] = result.bandit_results[i].estimated_probability; out_pull_counts[i] = result.bandit_results[i].times_pulled; } return 1; } catch (const std::exception& ex) { assign_error(error_message, ex.what()); return 0; } catch (...) { assign_error(error_message, "unknown C++ exception while collecting bandit results"); return 0; } }
void coolbox_free_bandit_agent(CoolBoxBanditAgentModel* model) { delete model; }

void coolbox_free_string(char* value) { std::free(value); }

} // extern "C"
