# FindAllDependencies.cmake
# Checks for all required dependencies and prints install instructions if missing.

set(_missing_deps)

if(WIN32)
    set(_coolbox_vcpkg_roots)
    if(DEFINED ENV{VCPKG_ROOT} AND NOT "$ENV{VCPKG_ROOT}" STREQUAL "")
        list(APPEND _coolbox_vcpkg_roots "$ENV{VCPKG_ROOT}")
    endif()
    if(DEFINED ENV{USERPROFILE} AND NOT "$ENV{USERPROFILE}" STREQUAL "")
        list(APPEND _coolbox_vcpkg_roots "$ENV{USERPROFILE}/vcpkg")
    endif()
    if(DEFINED ENV{LOCALAPPDATA} AND NOT "$ENV{LOCALAPPDATA}" STREQUAL "")
        list(APPEND _coolbox_vcpkg_roots "$ENV{LOCALAPPDATA}/vcpkg")
    endif()
    list(REMOVE_DUPLICATES _coolbox_vcpkg_roots)

    set(_coolbox_vcpkg_toolchain_file "")
    foreach(_vcpkg_root IN LISTS _coolbox_vcpkg_roots)
        if(EXISTS "${_vcpkg_root}/scripts/buildsystems/vcpkg.cmake")
            set(_coolbox_vcpkg_toolchain_file "${_vcpkg_root}/scripts/buildsystems/vcpkg.cmake")
            break()
        endif()
    endforeach()

    if(NOT _coolbox_vcpkg_toolchain_file STREQUAL "")
        foreach(_vcpkg_root IN LISTS _coolbox_vcpkg_roots)
            if(EXISTS "${_vcpkg_root}/installed/x64-windows")
                list(APPEND CMAKE_PREFIX_PATH
                    "${_vcpkg_root}/installed/x64-windows"
                    "${_vcpkg_root}/installed/x64-windows/share/gtest"
                    "${_vcpkg_root}/installed/x64-windows/share/gsl"
                    "${_vcpkg_root}/installed/x64-windows/lib/cmake/GTest"
                    "${_vcpkg_root}/installed/x64-windows/lib/cmake/GSL"
                )
            endif()
        endforeach()
        list(REMOVE_DUPLICATES CMAKE_PREFIX_PATH)
    endif()
endif()

# Check for CMake itself (should always be present)
if(NOT CMAKE_VERSION)
    list(APPEND _missing_deps "CMake (build tool)")
endif()

# Check for GTest
set(_gtest_required TRUE)
if(DEFINED BUILD_TESTING AND NOT BUILD_TESTING)
    set(_gtest_required FALSE)
elseif(DEFINED CACHE{BUILD_TESTING})
    get_property(_coolbox_build_testing CACHE BUILD_TESTING PROPERTY VALUE)
    if(NOT _coolbox_build_testing)
        set(_gtest_required FALSE)
    endif()
endif()

if(_gtest_required)
    set(_gtest_found FALSE)
    find_package(GTest QUIET)
    if(GTest_FOUND)
        set(_gtest_found TRUE)
    endif()
    if(NOT _gtest_found AND WIN32 AND NOT _coolbox_vcpkg_toolchain_file STREQUAL "")
        find_package(GTest QUIET)
        if(GTest_FOUND)
            set(_gtest_found TRUE)
        endif()
    endif()
    if(NOT _gtest_found)
        message(STATUS "GTest not found by dependency pre-check; configure will fall back to FetchContent while BUILD_TESTING=ON.")
    endif()
else()
    message(STATUS "BUILD_TESTING is OFF; skipping GTest dependency check.")
endif()

# Check for GSL
set(_gsl_required TRUE)
if(DEFINED ENABLE_GSL AND NOT ENABLE_GSL)
    set(_gsl_required FALSE)
elseif(DEFINED CACHE{ENABLE_GSL})
    get_property(_coolbox_enable_gsl CACHE ENABLE_GSL PROPERTY VALUE)
    if(NOT _coolbox_enable_gsl)
        set(_gsl_required FALSE)
    endif()
endif()

if(_gsl_required)
    set(_gsl_found FALSE)
    find_package(GSL QUIET)
    if(GSL_FOUND)
        set(_gsl_found TRUE)
    endif()
    if(NOT _gsl_found AND WIN32 AND NOT _coolbox_vcpkg_toolchain_file STREQUAL "")
        find_package(GSL QUIET)
        if(GSL_FOUND)
            set(_gsl_found TRUE)
        endif()
    endif()
    if(NOT _gsl_found)
        message(STATUS "GSL not found.")
        list(APPEND _missing_deps "GSL (GNU Scientific Library)\n  - Windows: vcpkg install gsl\n    If installed with vcpkg, ensure the vcpkg toolchain file is used or add the GSL cmake path to CMAKE_PREFIX_PATH.\n  - Ubuntu: sudo apt-get install libgsl-dev\n  - Mac: brew install gsl")
    endif()
else()
    message(STATUS "GSL support disabled for this configure (ENABLE_GSL=OFF); skipping GSL dependency check.")
endif()


# Check for Bison
set(_bison_found FALSE)
if(WIN32)
    # Check PATH first
    find_program(BISON_EXECUTABLE NAMES bison win_bison)
    # Also check default Chocolatey winflexbison location
    if(NOT BISON_EXECUTABLE)
        set(_bison_choco_path "C:/ProgramData/chocolatey/lib/winflexbison/tools/win_bison.exe")
        if(EXISTS "${_bison_choco_path}")
            set(BISON_EXECUTABLE "${_bison_choco_path}")
            set(_bison_found TRUE)
        endif()
    else()
        set(_bison_found TRUE)
    endif()
else()
    find_program(BISON_EXECUTABLE bison)
    if(BISON_EXECUTABLE)
        set(_bison_found TRUE)
    endif()
endif()
if(NOT _bison_found)
    message(STATUS "Bison not found.")
    if(WIN32)
        list(APPEND _missing_deps "Bison (parser generator)\n  - Windows: Run _scripts/install_bison.ps1 with:\n      powershell -ExecutionPolicy Bypass -File _scripts/install_bison.ps1\n    or manually install winflexbison and add to PATH.\n  - Ubuntu: sudo apt-get install bison\n  - Mac: brew install bison")
    else()
        list(APPEND _missing_deps "Bison (parser generator)\n  - Ubuntu: sudo apt-get install bison\n  - Mac: brew install bison")
    endif()
endif()


# Check for Doxygen
set(_doxygen_found FALSE)
if(WIN32)
    find_program(DOXYGEN_EXECUTABLE doxygen)
    if(NOT DOXYGEN_EXECUTABLE)
        set(_doxygen_bin "C:/Program Files/doxygen/bin/doxygen.exe")
        if(EXISTS "${_doxygen_bin}")
            set(DOXYGEN_EXECUTABLE "${_doxygen_bin}")
            set(_doxygen_found TRUE)
        endif()
    else()
        set(_doxygen_found TRUE)
    endif()
else()
    find_program(DOXYGEN_EXECUTABLE doxygen)
    if(DOXYGEN_EXECUTABLE)
        set(_doxygen_found TRUE)
    endif()
endif()
if(NOT _doxygen_found)
    message(STATUS "Doxygen not found.")
    if(WIN32)
        list(APPEND _missing_deps "Doxygen (documentation generator)\n  - Windows: Run _scripts/install_doxygen.ps1 or download from https://www.doxygen.nl/download.html\n    If you installed to a custom location, add the bin directory to your PATH.\n  - Ubuntu: sudo apt-get install doxygen\n  - Mac: brew install doxygen")
    else()
        list(APPEND _missing_deps "Doxygen (documentation generator)\n  - Ubuntu: sudo apt-get install doxygen\n  - Mac: brew install doxygen")
    endif()
endif()

# Check for vcpkg on Windows
if(WIN32)
    find_program(VCPKG_EXECUTABLE vcpkg)
    if(NOT VCPKG_EXECUTABLE AND NOT _coolbox_vcpkg_toolchain_file STREQUAL "")
        get_filename_component(_coolbox_vcpkg_root "${_coolbox_vcpkg_toolchain_file}" DIRECTORY)
        get_filename_component(_coolbox_vcpkg_root "${_coolbox_vcpkg_root}" DIRECTORY)
        get_filename_component(_coolbox_vcpkg_root "${_coolbox_vcpkg_root}" DIRECTORY)
        if(EXISTS "${_coolbox_vcpkg_root}/vcpkg.exe")
            set(VCPKG_EXECUTABLE "${_coolbox_vcpkg_root}/vcpkg.exe")
        endif()
    endif()
    if(NOT VCPKG_EXECUTABLE AND _coolbox_vcpkg_toolchain_file STREQUAL "")
        message(STATUS "vcpkg not found.")
        list(APPEND _missing_deps "vcpkg (C++ package manager)\n  - Download and install using the provided script:\n    powershell -ExecutionPolicy Bypass -File _scripts/install_vcpkg.ps1\n  - Or see: https://github.com/microsoft/vcpkg")
    endif()
endif()

# Print summary and exit if missing
if(_missing_deps)
    message(STATUS "\n==============================\nMissing dependencies detected:\n==============================")
    foreach(dep IN LISTS _missing_deps)
        message(STATUS "${dep}\n")
    endforeach()
    message(FATAL_ERROR "\nPlease install the missing dependencies above and re-run CMake.")
endif()
