# Configure C bindings for generate_purchase_c
name: 'purchase-configure-c-bindings'
description: 'Composite action for purchase-configure-c-bindings'
runs:
  using: 'composite'
  steps:
  - name: Configure C bindings
    shell: bash
    run: |
      cmake -S _deliverables/libraries/bindings/c_bindings -B _deliverables/libraries/bindings/c_bindings/build -DBUILD_TESTING=ON
